- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120hrs
    TRAINER: Siva
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{COURSE}} , Duration is {{DURATION}} , trained by {{TRAINER}}"
